/// Generates a Markdown research report from a completed ResearchSession.
///
/// This file has zero Flutter imports — pure Dart only.
library report_generator;

import 'dart:convert';
import 'dart:io';

import 'research_session.dart';

// ---------------------------------------------------------------------------
// ReportGenerator
// ---------------------------------------------------------------------------

/// Assembles and saves a Markdown research report.
class ReportGenerator {
  // -------------------------------------------------------------------------
  // Public API
  // -------------------------------------------------------------------------

  /// Generates the Markdown report and writes it to disk.
  ///
  /// Returns the absolute path of the saved report file.
  static Future<String> generate({
    required ResearchSession session,
    required List<String> characterNames,
    required List<String> sourceUrls,
  }) async {
    final content = _buildMarkdown(
      session: session,
      characterNames: characterNames,
      sourceUrls: sourceUrls,
    );

    final path = await _saveToDisk(session.sessionName, content);
    return path;
  }

  // -------------------------------------------------------------------------
  // Private: Markdown builder
  // -------------------------------------------------------------------------

  static String _buildMarkdown({
    required ResearchSession session,
    required List<String> characterNames,
    required List<String> sourceUrls,
  }) {
    final buf = StringBuffer();
    final dateStr = _formatDate(session.startTime);

    buf.writeln('# Research Report: ${session.topic}');
    buf.writeln();
    buf.writeln('**Date:** $dateStr');
    buf.writeln('**Session:** `${session.sessionName}`');
    buf.writeln('**Phase reached:** ${session.phase.name}');
    buf.writeln();
    buf.writeln('---');
    buf.writeln();

    // Per-character synthesis sections.
    buf.writeln('## Findings by Character');
    buf.writeln();
    for (final name in characterNames) {
      buf.writeln('### $name');
      buf.writeln();
      final synthesis = session.synthesisStatements[name];
      if (synthesis != null && synthesis.trim().isNotEmpty) {
        buf.writeln(synthesis.trim());
      } else {
        buf.writeln('_No synthesis statement recorded._');
      }
      final calls = session.toolCallCounts[name] ?? 0;
      buf.writeln();
      buf.writeln('> Tool calls made: $calls');
      buf.writeln();
    }

    buf.writeln('---');
    buf.writeln();

    // Consensus section — simple: find words that appear in 3+ syntheses.
    final consensus = _extractConsensusThemes(session, characterNames);
    buf.writeln('## Consensus & Common Themes');
    buf.writeln();
    if (consensus.isNotEmpty) {
      for (final theme in consensus) {
        buf.writeln('- $theme');
      }
    } else {
      buf.writeln('_Not enough synthesis data to extract consensus themes._');
    }
    buf.writeln();
    buf.writeln('---');
    buf.writeln();

    // Sources.
    buf.writeln('## Sources');
    buf.writeln();
    if (sourceUrls.isNotEmpty) {
      final uniqueUrls = sourceUrls.toSet().toList();
      for (final url in uniqueUrls) {
        buf.writeln('- $url');
      }
    } else {
      buf.writeln('_No URLs recorded during this session._');
    }
    buf.writeln();
    buf.writeln('---');
    buf.writeln();
    buf.writeln(
        '_Generated by deepThinkER Autonomous Research Mode — ${_formatDate(DateTime.now())}_');

    return buf.toString();
  }

  /// Very simple consensus extraction: tokenise all syntheses, find words
  /// that appear in >= 3 character syntheses (excluding stopwords).
  static List<String> _extractConsensusThemes(
    ResearchSession session,
    List<String> characterNames,
  ) {
    const stopwords = {
      'the', 'a', 'an', 'and', 'or', 'but', 'in', 'on', 'at', 'to', 'for',
      'of', 'with', 'by', 'from', 'as', 'is', 'was', 'are', 'were', 'be',
      'been', 'being', 'have', 'has', 'had', 'do', 'does', 'did', 'will',
      'would', 'could', 'should', 'may', 'might', 'that', 'this', 'these',
      'those', 'it', 'its', 'i', 'we', 'they', 'he', 'she', 'you', 'not',
    };

    // Per-character word sets.
    final charWordSets = <String, Set<String>>{};
    for (final name in characterNames) {
      final text = session.synthesisStatements[name] ?? '';
      final words = text
          .toLowerCase()
          .replaceAll(RegExp(r'[^a-z0-9 ]'), ' ')
          .split(RegExp(r'\s+'))
          .where((w) => w.length > 4 && !stopwords.contains(w))
          .toSet();
      charWordSets[name] = words;
    }

    // Count how many characters mention each word.
    final wordCounts = <String, int>{};
    for (final words in charWordSets.values) {
      for (final word in words) {
        wordCounts[word] = (wordCounts[word] ?? 0) + 1;
      }
    }

    // Words mentioned by 3+ characters (or 2+ if fewer than 4 have synthesised).
    final minCount =
        session.synthesisStatements.length >= 3 ? 3 : 2;
    final themes = wordCounts.entries
        .where((e) => e.value >= minCount)
        .map((e) => e.key)
        .toList()
      ..sort();

    // Return top 10 themes.
    return themes.take(10).toList();
  }

  // -------------------------------------------------------------------------
  // Private: File I/O
  // -------------------------------------------------------------------------

  static Future<String> _saveToDisk(
      String sessionName, String content) async {
    final reportsDir = _reportsDir();
    await Directory(reportsDir).create(recursive: true);
    final filePath =
        [reportsDir, '$sessionName.md'].join(Platform.pathSeparator);
    await File(filePath).writeAsString(content, encoding: utf8);
    return filePath;
  }

  static String _reportsDir() {
    final home = Platform.isWindows
        ? Platform.environment['USERPROFILE']
        : Platform.environment['HOME'];
    if (home == null || home.isEmpty) {
      throw StateError('Cannot determine home directory.');
    }
    return [home, 'Documents', 'deepThinkER', 'reports']
        .join(Platform.pathSeparator);
  }

  static String _formatDate(DateTime dt) {
    final d = dt.toLocal();
    return '${d.year}-${_p(d.month)}-${_p(d.day)} '
        '${_p(d.hour)}:${_p(d.minute)}';
  }

  static String _p(int v) => v.toString().padLeft(2, '0');
}
